export const officialDocsCatalog = Object.freeze([
  {
    id: 'aws-docs',
    title: 'AWS Documentation',
    description: 'Official documentation for Amazon Web Services products and architecture.',
    author: 'Amazon Web Services',
    url: 'https://docs.aws.amazon.com/',
    tags: ['aws', 'cloud', 'cloud computing', 'devops', 'deployment'],
  },
  {
    id: 'docker-docs',
    title: 'Docker Documentation',
    description: 'Official guides and references for containers, images, and Docker tooling.',
    author: 'Docker',
    url: 'https://docs.docker.com/',
    tags: ['docker', 'containers', 'devops', 'deployment'],
  },
  {
    id: 'express-docs',
    title: 'Express Documentation',
    description: 'Official web framework documentation for Express on Node.js.',
    author: 'OpenJS Foundation',
    url: 'https://expressjs.com/',
    tags: ['express', 'node', 'node.js', 'backend', 'api'],
  },
  {
    id: 'git-docs',
    title: 'Git Reference Documentation',
    description: 'Official Git reference, book, and command documentation.',
    author: 'Git Project',
    url: 'https://git-scm.com/doc',
    tags: ['git', 'version control', 'collaboration'],
  },
  {
    id: 'github-docs',
    title: 'GitHub Documentation',
    description: 'Official GitHub documentation for repositories, Actions, and collaboration.',
    author: 'GitHub',
    url: 'https://docs.github.com/',
    tags: ['github', 'git', 'github actions', 'collaboration', 'ci/cd'],
  },
  {
    id: 'kubernetes-docs',
    title: 'Kubernetes Documentation',
    description: 'Official concepts, tutorials, tasks, and reference documentation for Kubernetes.',
    author: 'Cloud Native Computing Foundation',
    url: 'https://kubernetes.io/docs/',
    tags: ['kubernetes', 'containers', 'orchestration', 'devops', 'cloud'],
  },
  {
    id: 'mdn-web-docs',
    title: 'MDN Web Docs',
    description: 'Authoritative documentation for HTML, CSS, JavaScript, and Web APIs.',
    author: 'Mozilla',
    url: 'https://developer.mozilla.org/docs/Web',
    tags: ['html', 'css', 'javascript', 'web', 'frontend', 'web api'],
  },
  {
    id: 'microsoft-learn',
    title: 'Microsoft Learn',
    description: 'Official Microsoft learning documentation for Azure, .NET, and developer tools.',
    author: 'Microsoft',
    url: 'https://learn.microsoft.com/docs/',
    tags: ['azure', 'microsoft', '.net', 'c#', 'cloud'],
  },
  {
    id: 'mongodb-docs',
    title: 'MongoDB Documentation',
    description: 'Official MongoDB manuals, driver documentation, and operational guides.',
    author: 'MongoDB',
    url: 'https://www.mongodb.com/docs/',
    tags: ['mongodb', 'database', 'nosql', 'mongoose'],
  },
  {
    id: 'node-docs',
    title: 'Node.js Documentation',
    description: 'Official Node.js API reference and learning materials.',
    author: 'OpenJS Foundation',
    url: 'https://nodejs.org/docs/latest/api/',
    tags: ['node', 'node.js', 'javascript', 'backend', 'api'],
  },
  {
    id: 'python-docs',
    title: 'Python Documentation',
    description: 'Official Python language tutorial, library reference, and guides.',
    author: 'Python Software Foundation',
    url: 'https://docs.python.org/3/',
    tags: ['python', 'programming', 'backend', 'data science', 'machine learning'],
  },
  {
    id: 'react-docs',
    title: 'React Documentation',
    description: 'Official React guides, API reference, and interactive learning material.',
    author: 'React Team',
    url: 'https://react.dev/',
    tags: ['react', 'react hooks', 'javascript', 'frontend', 'web'],
  },
  {
    id: 'typescript-docs',
    title: 'TypeScript Documentation',
    description: 'Official TypeScript handbook, reference, and release documentation.',
    author: 'Microsoft',
    url: 'https://www.typescriptlang.org/docs/',
    tags: ['typescript', 'javascript', 'frontend', 'backend'],
  },
]);
